import Head from 'next/head'
import SearchBox from '../components/SearchBox'
import JobsList from '../components/JobsList';
import Axios from "axios";

export const getStaticProps = async ()=>{
  try {
      const res = await Axios.get("https://my.api.mockaroo.com/jobs_api.json?key=98d847b0");
      return {
         props:{data:res.data}
      }
  
  } catch (error) {
      return error
  }
 
}



export default function Home({data}) {
  
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SearchBox/>
      <JobsList data = {data}/>
    
      
    </>
  )
}
